package sic;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Angela
 */
public class Fondo extends javax.swing.JPanel {

    /**
     * Creates new form Fondo
     */
    public Fondo() {
        initComponents();
        this.setSize(618,450);
        
    }
   
    @Override
    public void paintComponent(Graphics g){
        Dimension tam = getSize();
        
        ImageIcon imagenfondo = new ImageIcon(new ImageIcon(getClass().getResource("/imagenes/fondoprincipal.jpg")).getImage());
        g.drawImage(imagenfondo.getImage(),0,0, tam.width, tam.height, null); 
        setOpaque(false);
        super.paintComponent(g);     
        
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(440, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
